-- Esquema de Vista 360 del Estudiante.

CREATE TABLE programa (
    codigo       VARCHAR2(10)  NOT NULL,
    nombre       VARCHAR2(150) NOT NULL,
    origen       VARCHAR2(10)  NOT NULL,
    fecha_corte  TIMESTAMP     NOT NULL,
    CONSTRAINT pk_programa PRIMARY KEY (codigo),
    CONSTRAINT ck_programa_origen CHECK (origen IN ('ERP', 'LMS'))
);
COMMENT ON TABLE programa IS 'Catalogo de programas academicos. Replica del ERP (S-01, S-12).';

CREATE TABLE periodo_academico (
    codigo        VARCHAR2(6) NOT NULL,
    fecha_inicio  DATE        NOT NULL,
    fecha_fin     DATE        NOT NULL,
    origen        VARCHAR2(10) NOT NULL,
    fecha_corte   TIMESTAMP    NOT NULL,
    CONSTRAINT pk_periodo PRIMARY KEY (codigo),
    CONSTRAINT ck_periodo_fechas CHECK (fecha_fin > fecha_inicio),
    CONSTRAINT ck_periodo_origen CHECK (origen IN ('ERP', 'LMS'))
);
COMMENT ON TABLE periodo_academico IS 'Periodos academicos. El vigente delimita que devuelve el servicio (S-14).';

CREATE TABLE estudiante (
    codigo_institucional  VARCHAR2(9)   NOT NULL,
    nombres               VARCHAR2(100) NOT NULL,
    apellidos             VARCHAR2(100) NOT NULL,
    correo                VARCHAR2(150),
    origen                VARCHAR2(10)  NOT NULL,
    fecha_corte           TIMESTAMP     NOT NULL,
    CONSTRAINT pk_estudiante PRIMARY KEY (codigo_institucional),
    CONSTRAINT ck_estudiante_codigo CHECK (codigo_institucional LIKE 'A00______'),
    CONSTRAINT ck_estudiante_origen CHECK (origen IN ('ERP', 'LMS'))
);
COMMENT ON TABLE estudiante IS 'Replica de identidad academica. (S-01, S-11).';

CREATE TABLE asignatura (
    codigo       VARCHAR2(5)   NOT NULL,
    nombre       VARCHAR2(200) NOT NULL,
    creditos     NUMBER(2)     NOT NULL,
    origen       VARCHAR2(10)  NOT NULL,
    fecha_corte  TIMESTAMP     NOT NULL,
    CONSTRAINT pk_asignatura PRIMARY KEY (codigo),
    CONSTRAINT ck_asignatura_creditos CHECK (creditos >= 0),
    CONSTRAINT ck_asignatura_origen CHECK (origen IN ('ERP', 'LMS'))
);
COMMENT ON TABLE asignatura IS 'Catalogo de asignaturas. (S-15).';

CREATE TABLE grupo_curso (
    id                 NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    nrc                VARCHAR2(5)   NOT NULL,
    periodo_codigo     VARCHAR2(6)   NOT NULL,
    asignatura_codigo  VARCHAR2(5)   NOT NULL,
    grupo              VARCHAR2(3)   NOT NULL,
    docente            VARCHAR2(150) NOT NULL,
    origen             VARCHAR2(10)  NOT NULL,
    fecha_corte        TIMESTAMP     NOT NULL,
    CONSTRAINT pk_grupo_curso PRIMARY KEY (id),
    CONSTRAINT uq_grupo_curso_nrc UNIQUE (nrc, periodo_codigo),
    CONSTRAINT fk_grupo_curso_periodo FOREIGN KEY (periodo_codigo) REFERENCES periodo_academico (codigo),
    CONSTRAINT fk_grupo_curso_asignatura FOREIGN KEY (asignatura_codigo) REFERENCES asignatura (codigo),
    CONSTRAINT ck_grupo_curso_origen CHECK (origen IN ('ERP', 'LMS'))
);
COMMENT ON TABLE grupo_curso IS 'El grupo como fila.';

CREATE TABLE matricula (
    id                 NUMBER(19)  GENERATED BY DEFAULT AS IDENTITY,
    estudiante_codigo  VARCHAR2(9) NOT NULL,
    periodo_codigo     VARCHAR2(6) NOT NULL,
    origen             VARCHAR2(10) NOT NULL,
    fecha_corte        TIMESTAMP    NOT NULL,
    CONSTRAINT pk_matricula PRIMARY KEY (id),
    CONSTRAINT uq_matricula UNIQUE (estudiante_codigo, periodo_codigo),
    CONSTRAINT fk_matricula_estudiante FOREIGN KEY (estudiante_codigo) REFERENCES estudiante (codigo_institucional),
    CONSTRAINT fk_matricula_periodo FOREIGN KEY (periodo_codigo) REFERENCES periodo_academico (codigo),
    CONSTRAINT ck_matricula_origen CHECK (origen IN ('ERP', 'LMS'))
);
COMMENT ON TABLE matricula IS 'Acto semestral. (S-14).';

CREATE TABLE matricula_programa (
    id               NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    matricula_id     NUMBER(19)   NOT NULL,
    programa_codigo  VARCHAR2(10) NOT NULL,
    orden            NUMBER(2)    NOT NULL,
    CONSTRAINT pk_matricula_programa PRIMARY KEY (id),
    CONSTRAINT uq_matricula_programa UNIQUE (matricula_id, programa_codigo),
    CONSTRAINT uq_matricula_programa_orden UNIQUE (matricula_id, orden),
    CONSTRAINT fk_matricula_programa_matricula FOREIGN KEY (matricula_id) REFERENCES matricula (id),
    CONSTRAINT fk_matricula_programa_programa FOREIGN KEY (programa_codigo) REFERENCES programa (codigo),
    CONSTRAINT ck_matricula_programa_orden CHECK (orden >= 1)
);
COMMENT ON TABLE matricula_programa IS 'Doble titulacion (S-09). ';

CREATE TABLE inscripcion (
    id                   NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    matricula_id         NUMBER(19)   NOT NULL,
    asignatura_codigo    VARCHAR2(5)  NOT NULL,
    grupo_curso_id       NUMBER(19)   NOT NULL,
    programa_codigo      VARCHAR2(10) NOT NULL,
    estado_inscripcion   VARCHAR2(10) NOT NULL,
    fecha_cancelacion    DATE,
    escala_calificacion  VARCHAR2(10) NOT NULL,
    estado_calificacion  VARCHAR2(11) NOT NULL,
    nota                 NUMBER(3,2),
    resultado            VARCHAR2(10),
    origen               VARCHAR2(10) NOT NULL,
    fecha_corte          TIMESTAMP    NOT NULL,
    CONSTRAINT pk_inscripcion PRIMARY KEY (id),
    CONSTRAINT uq_inscripcion UNIQUE (matricula_id, asignatura_codigo),
    CONSTRAINT fk_inscripcion_matricula FOREIGN KEY (matricula_id) REFERENCES matricula (id),
    CONSTRAINT fk_inscripcion_asignatura FOREIGN KEY (asignatura_codigo) REFERENCES asignatura (codigo),
    CONSTRAINT fk_inscripcion_grupo FOREIGN KEY (grupo_curso_id) REFERENCES grupo_curso (id),
    CONSTRAINT fk_inscripcion_programa FOREIGN KEY (programa_codigo) REFERENCES programa (codigo),
    CONSTRAINT ck_inscripcion_estado CHECK (estado_inscripcion IN ('INSCRITA', 'CANCELADA')),
    CONSTRAINT ck_inscripcion_escala CHECK (escala_calificacion IN ('NUMERICA', 'APROBACION')),
    CONSTRAINT ck_inscripcion_calif CHECK (estado_calificacion IN ('PENDIENTE', 'PARCIAL', 'DEFINITIVA')),
    CONSTRAINT ck_inscripcion_resultado CHECK (resultado IS NULL OR resultado IN ('APROBADA', 'REPROBADA')),
    CONSTRAINT ck_inscripcion_origen CHECK (origen IN ('ERP', 'LMS')),
    
    CONSTRAINT ck_inscripcion_cancelacion CHECK (
        (estado_inscripcion = 'CANCELADA' AND fecha_cancelacion IS NOT NULL)
     OR (estado_inscripcion = 'INSCRITA'  AND fecha_cancelacion IS NULL)),
    CONSTRAINT ck_inscripcion_pendiente CHECK (
        estado_calificacion <> 'PENDIENTE' OR (nota IS NULL AND resultado IS NULL)),
    CONSTRAINT ck_inscripcion_numerica CHECK (
        escala_calificacion <> 'NUMERICA'
     OR (resultado IS NULL AND (estado_calificacion = 'PENDIENTE' OR nota IS NOT NULL))),
    CONSTRAINT ck_inscripcion_aprobacion CHECK (
        escala_calificacion <> 'APROBACION'
     OR (nota IS NULL
         AND estado_calificacion IN ('PENDIENTE', 'DEFINITIVA')
         AND (estado_calificacion = 'PENDIENTE' OR resultado IS NOT NULL))),
    CONSTRAINT ck_inscripcion_nota CHECK (nota IS NULL OR (nota >= 0 AND nota <= 5))
);
COMMENT ON TABLE inscripcion IS 'Una inscripcion (S-15).';

CREATE TABLE condicion_academica (
    id                 NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    estudiante_codigo  VARCHAR2(9)  NOT NULL,
    programa_codigo    VARCHAR2(10) NOT NULL,
    periodo_codigo     VARCHAR2(6)  NOT NULL,
    condicion          VARCHAR2(30) NOT NULL,
    condicion_anterior VARCHAR2(30),
    vigente_desde      TIMESTAMP    NOT NULL,
    vigente_hasta      TIMESTAMP,
    origen             VARCHAR2(10) NOT NULL,
    fecha_corte        TIMESTAMP    NOT NULL,
    CONSTRAINT pk_condicion PRIMARY KEY (id),
    CONSTRAINT fk_condicion_estudiante FOREIGN KEY (estudiante_codigo) REFERENCES estudiante (codigo_institucional),
    CONSTRAINT fk_condicion_programa FOREIGN KEY (programa_codigo) REFERENCES programa (codigo),
    CONSTRAINT fk_condicion_periodo FOREIGN KEY (periodo_codigo) REFERENCES periodo_academico (codigo),
    CONSTRAINT ck_condicion_vigencia CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde),
    CONSTRAINT ck_condicion_origen CHECK (origen IN ('ERP', 'LMS'))
);
COMMENT ON TABLE condicion_academica IS 'Historial de la condicion que declara el ERP, con la anterior de cada transicion. ';


-- Datos propios de Vista 360 (S-05, S-06, S-07, S-12)

CREATE TABLE asignacion_acompanamiento (
    id                 NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    estudiante_codigo  VARCHAR2(9)  NOT NULL,
    acompanante_id     VARCHAR2(50) NOT NULL,
    vigente_desde      DATE         NOT NULL,
    vigente_hasta      DATE,
    creado_en          TIMESTAMP    NOT NULL,
    CONSTRAINT pk_asignacion PRIMARY KEY (id),
    CONSTRAINT fk_asignacion_estudiante FOREIGN KEY (estudiante_codigo) REFERENCES estudiante (codigo_institucional),
    CONSTRAINT ck_asignacion_vigencia CHECK (vigente_hasta IS NULL OR vigente_hasta >= vigente_desde)
);
COMMENT ON TABLE asignacion_acompanamiento IS 'Vinculo estudiante-acompanante, dato propio (S-05).';

CREATE TABLE reporte_acompanamiento (
    id                 NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    estudiante_codigo  VARCHAR2(9)  NOT NULL,
    acompanante_id     VARCHAR2(50) NOT NULL,
    tipo_contacto      VARCHAR2(30) NOT NULL,
    canal              VARCHAR2(20) NOT NULL,
    ocurrido_en        TIMESTAMP    NOT NULL,
    registrado_en      TIMESTAMP    NOT NULL,
    tiene_detalle      NUMBER(1)    NOT NULL,
    CONSTRAINT pk_reporte PRIMARY KEY (id),
    CONSTRAINT fk_reporte_estudiante FOREIGN KEY (estudiante_codigo) REFERENCES estudiante (codigo_institucional),
    CONSTRAINT ck_reporte_detalle CHECK (tiene_detalle IN (0, 1))
);
COMMENT ON TABLE reporte_acompanamiento IS 'El hecho estructurado del contacto, sin texto libre (S-06).';

CREATE TABLE reporte_acompanamiento_detalle (
    reporte_id                  NUMBER(19)   NOT NULL,
    texto                       CLOB         NOT NULL,
    clasificacion_sensibilidad  VARCHAR2(20) NOT NULL,
    CONSTRAINT pk_reporte_detalle PRIMARY KEY (reporte_id),
    CONSTRAINT fk_reporte_detalle FOREIGN KEY (reporte_id) REFERENCES reporte_acompanamiento (id)
);
COMMENT ON TABLE reporte_acompanamiento_detalle IS 'El relato sensible, en tabla aparte (S-06).';

CREATE TABLE alerta (
    id                 NUMBER(19)   GENERATED BY DEFAULT AS IDENTITY,
    estudiante_codigo  VARCHAR2(9)  NOT NULL,
    tipo               VARCHAR2(40) NOT NULL,
    severidad          VARCHAR2(10) NOT NULL,
    origen_senal       VARCHAR2(30) NOT NULL,
    detectada_en       TIMESTAMP    NOT NULL,
    estado             VARCHAR2(20) NOT NULL,
    cerrada_en         TIMESTAMP,
    CONSTRAINT pk_alerta PRIMARY KEY (id),
    CONSTRAINT fk_alerta_estudiante FOREIGN KEY (estudiante_codigo) REFERENCES estudiante (codigo_institucional),
    CONSTRAINT ck_alerta_severidad CHECK (severidad IN ('BAJA', 'MEDIA', 'ALTA')),
    CONSTRAINT ck_alerta_estado CHECK (estado IN ('ABIERTA', 'EN_GESTION', 'CERRADA'))
);
COMMENT ON TABLE alerta IS 'Dato propio (S-07, S-12).';

CREATE TABLE solicitud (
    id                 NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    estudiante_codigo  VARCHAR2(9)   NOT NULL,
    tipo               VARCHAR2(40)  NOT NULL,
    estado             VARCHAR2(20)  NOT NULL,
    resumen            VARCHAR2(500) NOT NULL,
    creada_en          TIMESTAMP     NOT NULL,
    actualizada_en     TIMESTAMP     NOT NULL,
    CONSTRAINT pk_solicitud PRIMARY KEY (id),
    CONSTRAINT fk_solicitud_estudiante FOREIGN KEY (estudiante_codigo) REFERENCES estudiante (codigo_institucional),
    CONSTRAINT ck_solicitud_estado CHECK (estado IN ('ABIERTA', 'EN_TRAMITE', 'RESUELTA', 'CERRADA'))
);
COMMENT ON TABLE solicitud IS 'Dato propio (S-07, S-12).';

CREATE TABLE evento_salida (
    id             NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    tipo_evento    VARCHAR2(60)  NOT NULL,
    agregado_tipo  VARCHAR2(40)  NOT NULL,
    agregado_id    VARCHAR2(64)  NOT NULL,
    carga          CLOB          NOT NULL,
    creado_en      TIMESTAMP     NOT NULL,
    publicado_en   TIMESTAMP,
    intentos       NUMBER(3)     DEFAULT 0 NOT NULL,
    ultimo_error   VARCHAR2(500),
    CONSTRAINT pk_evento_salida PRIMARY KEY (id),
    CONSTRAINT ck_evento_salida_intentos CHECK (intentos >= 0)
);
COMMENT ON TABLE evento_salida IS 'Registro de salida tipo outbox (S-07).';


-- ===========================================================================
-- Operacion (Partes 3 y 4)
-- ===========================================================================

CREATE TABLE auditoria_acceso (
    id                     NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
    ocurrido_en            TIMESTAMP     NOT NULL,
    sujeto_id              VARCHAR2(50)  NOT NULL,
    sujeto_tipo            VARCHAR2(20)  NOT NULL,
    rol                    VARCHAR2(30)  NOT NULL,
    estudiante_consultado  VARCHAR2(9),
    recurso                VARCHAR2(200) NOT NULL,
    operacion              VARCHAR2(10)  NOT NULL,
    resultado              VARCHAR2(20)  NOT NULL,
    direccion_ip           VARCHAR2(45),
    agente_usuario         VARCHAR2(300),
    correlacion_id         VARCHAR2(64)  NOT NULL,
    CONSTRAINT pk_auditoria PRIMARY KEY (id),
    CONSTRAINT ck_auditoria_sujeto CHECK (sujeto_tipo IN ('PERSONA', 'SERVICIO')),
    CONSTRAINT ck_auditoria_resultado CHECK (resultado IN ('PERMITIDO', 'DENEGADO'))
);
COMMENT ON TABLE auditoria_acceso IS 'Quien consulto que, cuando y desde donde. Escenario 4B. Registra tambien los accesos denegados, porque un intento rechazado es parte de la respuesta. correlacion_id enlaza la consulta con toda la cadena de servicios (S-10).';

CREATE TABLE marca_agua_sondeo (
    fuente             VARCHAR2(30)  NOT NULL,
    entidad            VARCHAR2(40)  NOT NULL,
    ultimo_corte       TIMESTAMP     NOT NULL,
    ultima_ejecucion   TIMESTAMP,
    registros_leidos   NUMBER(10),
    estado             VARCHAR2(20)  NOT NULL,
    ultimo_error       VARCHAR2(500),
    CONSTRAINT pk_marca_agua PRIMARY KEY (fuente, entidad),
    CONSTRAINT ck_marca_agua_fuente CHECK (fuente IN ('ERP', 'LMS')),
    CONSTRAINT ck_marca_agua_estado CHECK (estado IN ('OK', 'DEGRADADO', 'FALLIDO'))
);
COMMENT ON TABLE marca_agua_sondeo IS 'Hasta que momento se leyo cada entidad de cada fuente (S-02). 4A';
